# -*- coding: utf-8 -*-
"""utils_featurizers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wA5EGI05cy6DFhg_Ysk0r101lesEt1WO
"""

# utils_featurizers.py
"""
Centralized molecule processing and featurization utilities.
"""
import numpy as np
import torch
from rdkit import Chem
from rdkit.Chem import Descriptors
from typing import List, Optional

class MoleculeProcessor:
    """Handles conversion from SMILES to graph objects for the GNN."""

    def __init__(self, descriptor_scaler=None):
        # The scaler is not needed for the hybrid model featurization
        print(" MoleculeProcessor initialized for GNN embedding.")

    def smiles_to_graph(self, smiles: str):
        if not smiles or not isinstance(smiles, str):
            return None

        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None

        # --- CORRECTED ATOM FEATURES (dim=2) with proper dtype ---
        # The GNN was trained with only 2 features per atom.
        atom_features = []
        for atom in mol.GetAtoms():
            atom_features.append([
                float(atom.GetAtomicNum()),  # Feature 1: Atomic Number (as float)
                float(atom.GetDegree())      # Feature 2: Atom Degree (as float)
            ])

        edge_indices = [[b.GetBeginAtomIdx(), b.GetEndAtomIdx()] for b in mol.GetBonds()]

        from torch_geometric.data import Data

        return Data(
            x=torch.tensor(atom_features, dtype=torch.float32),  # explicit float32
            edge_index=torch.tensor(edge_indices, dtype=torch.long).t().contiguous() if edge_indices else torch.empty((2, 0), dtype=torch.long)
        )